# Generated by Django 3.0.3 on 2020-02-13 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_addr', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('max_occupancy', models.IntegerField()),
                ('housing_type', models.CharField(max_length=10)),
                ('rent_amt', models.IntegerField()),
                ('sq_ft', models.IntegerField()),
                ('no_bdr', models.IntegerField()),
                ('no_bath', models.IntegerField()),
                ('pkg_type', models.CharField(max_length=20)),
                ('term_mo', models.IntegerField()),
                ('ada', models.CharField(blank=True, max_length=100, null=True)),
                ('pets', models.CharField(max_length=10)),
                ('furnished', models.BooleanField()),
                ('smoking', models.BooleanField()),
                ('no_app_fee', models.BooleanField()),
                ('no_broker_fee', models.BooleanField()),
                ('img', models.ImageField(default='default.jpg', upload_to='home_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
